services:
  postgres:
    image: postgres:16-alpine
    container_name: shortly-database
    restart: always
    env_file: ./services/shortly-api-service/.env
    ports:
      - "5432:5432"
    volumes:
      - shortly-database-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: kgs-redis-queue
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - shortly-kgs-queue:/data

volumes:
  shortly-database-data:
  shortly-kgs-queue:
