FROM golang:1.24.2-alpine

WORKDIR /app

COPY proto/shortly-proto /proto/shortly-proto

COPY services/shortly-kgs-service/go.mod services/shortly-kgs-service/go.sum ./

RUN go mod download

COPY services/shortly-kgs-service/ .

RUN go build -o kgs-service ./cmd

EXPOSE 2000

EXPOSE 8081

CMD ["./kgs-service"]
